import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import profilePic from "../../public/images/profile/profilePic.png"
import { motion } from "framer-motion"


import Animatetext from '@/components/Animatetext'



const pPic = {
  initial: {
    opacity: 0,
    x: 50,
  },
  animate: {
    opacity: 1,
    x: 0,
    transition: {
      duration: 1,
    }

  }
}

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className='flex item-center justify-between w-full'>
            <div className='w-[60%] border'>
              <Animatetext text="As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications.
                Explore my latest projects and articles, showcasing my expertise in React.js and web development."/>
            </div>
            <motion.div className='w-[40%] pl-[50px] border' variants={pPic} initial="initial"
              animate="animate">
              <Image src={profilePic} alt="Profile Photo" className='width-full h-auto' ></Image>
            </motion.div>
          </div>
        </Layout>
      </main>
    </>
  )
}
